### PR TITLE
Submissions

### PR DESCRIPTION
**Pull request by onyeepeace**
corrected the mistake with my ID.

### CODE REVIEW

**Comment by timmyCoder** [comment]
If you want to change or modify your already submitted file, you can:
1. go to the submissions branch of the HNG repo.
2. Fork it
3. Locate your script and make your change
4. Then make a Pull Request back to submissions.

**Comment by timmyCoder** [comment]
you still have a conflict

**Comment by onyeepeace** [comment]
Please I need help. What do I do?

**Comment by timmyCoder** [comment]
check what is causing the error online here, and fix in your IDE, then make a new PR

**Comment by onyeepeace** [comment]
I have fixed it now

**Pull request merged**
