### PR TITLE
HNG-04921 added a JS script file to output desired result

### PR DESCRIPTION
**Pull request by nwazuo**
I added a script file to output desired result and followed other instructions given in team-falcon channel.

### CODE REVIEW

**Comment by techiefer** [comment]
what's the problem here stopping it from merging

**Comment by anubabajide** [comment]
A change in another file. I'd have to resolve the merge conflict manually

**Comment by nwazuo** [comment]
But... I didn't make any changes to the other files. I just simply forked your master branch and uploaded a new file and committed it.

Did I do anything wrongly?

**Comment by anubabajide** [comment]
sorry for the delay

**Pull request merged**
