### PR TITLE
add Index php

### PR DESCRIPTION
**Pull request by usmansbk**
Currently executes javascript and python scripts. We'll be adding more types later

### CODE REVIEW

**Comment by saucecodee** [comment]
Please only script files are allowed

**Comment by usmansbk** [comment]
@saucecodee that's the index.php file that will run the scripts

**Comment by usmansbk** [comment]
Also @saucecodee  why are some of the script in the index folder. It doesn't adhere to the recommended folder structure. Please move them to the script folder.

**Comment by saucecodee** [comment]
The index.php file is already set. You just have to add your script

**Comment by techiefer** [comment]
yeah @usmansbk we're working on moving them to the scrips folder

**Comment by techiefer** [comment]
also @usmansbk nice work btw

**Comment by usmansbk** [comment]
@saucecodee  can I get a copy of it?

**Comment by techiefer** [comment]
@saucecodee the index.php file won't be merged to the submission branch but to the development branch

**Comment by techiefer** [comment]
@usmansbk a copy of what

**Comment by saucecodee** [comment]
@usmansbk The copy is already on the repo you don't need to bother about it now. Just edit your PR and removed the index.js file so that I can merge.

 Also, remember to make PR to the submission branch

**Comment by techiefer** [comment]
@saucodee, he is going to make the PR to the development branch instead of the submission because he is part of the backend guys i guess.

**Comment by saucecodee** [comment]
@techiefer  I'm also part of the backend team. We need only one index.php file and we already have one. 

Adding his own will cause a merge conflict. The instruction was to push only the script file. The team lead has the index.php file under control

**Comment by techiefer** [comment]
okay @saucecodee didnt know

**Pull request closed without merging**
