### PR TITLE
HNG-00869.py

### PR DESCRIPTION
**Pull request by DevTobii**
I have updated my stage two task

### CODE REVIEW

**Comment by timmyCoder** [comment]
please resolve conflicts in your submission branch

**Comment by DevTobii** [comment]
> please resolve conflicts in your submission branch

Please how do i resolve it, I have been on it since morning

**Comment by timmyCoder** [comment]
i think what you can do right now is to just fork the repo again and reopen the pull request

**Comment by timmyCoder** [comment]
because we're working on other files

**Comment by DevTobii** [comment]
Can I delete the entire repo? Before forking it again?

On 3 Jun 2020 5:03 pm, "Olatoye Daniel" <notifications@github.com> wrote:

i think what you can do right now is to just fork the repo again and reopen
the pull request

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/anubabajide/HNG-Task-2-Team-Falcon/pull/462#issuecomment-638293082>,
or unsubscribe

**Comment by timmyCoder** [comment]
yeah that can work

**Comment by DevTobii** [comment]
I created a new pull request, i cant make a commit, check out the
screenshot....what do you think?

**Comment by timmyCoder** [comment]
there are still conflicts with our submission branch
please if you don't resolve them, we would have problems hosting it
i hope you understand

**Comment by timmyCoder** [comment]
if i can help you merge your file, which one do you want to submit?

**Comment by DevTobii** [comment]
I did it, kindly confirm if I pass the task. thank you

**Comment by timmyCoder** [comment]
I can't say if any task have been passed yet
wait for the task to be run on the server and you'd get an update

**Pull request closed without merging**
