### PR TITLE
HNG-03967 email_correction

### PR DESCRIPTION
**Pull request by Kingsleyamoke**

### CODE REVIEW

**Comment by timmyCoder** [comment]
please move your file to the script folder

**Comment by Kingsleyamoke** [comment]
pls how can i remove my file fromt he folder

**Comment by Kingsleyamoke** [comment]
Please, help me and remove other files except the last one, there was a in
my email address in the previous file before this last file.

I am unable to remove the file by myself.

Thank you.

**Comment by timmyCoder** [comment]
i think you have to do it from your end
prolly fork the repo again and add it under the script folder

**Comment by techiefer** [comment]
you could by in your local machine code, copy and paste the code into the scripts folder.
then upload and make a PR

**Comment by anubabajide** [comment]
You have 4 different files you are adding with no extension.
Please send only one valid file in the scripts folder

**Pull request closed without merging**
