### PR TITLE
Created HNG-00253.py

### PR DESCRIPTION
**Pull request by KehindeBello**

### CODE REVIEW

**Comment by timmyCoder** [comment]
please move your file to the script folder

**Comment by KehindeBello** [comment]
Can u explain better please, because i created it in the script folder in the first place...

**Comment by timmyCoder** [comment]
when you forked the repo, open the script folder and create your new file there

**Comment by KehindeBello** [comment]
I just checked and it is under the script folder, or is it under the master branch of the forked repo i should do it?

**Comment by timmyCoder** [comment]
create it under script in the submissions branch

**Comment by KehindeBello** [comment]
Am lost honestly! i found one outside the script folder, and i found another in the script folder, so i deleted the one outside scripts...
I don't mean to trouble you assist me please!

**Pull request closed without merging**
