### PR TITLE
HNG Task 2

### PR DESCRIPTION
**Pull request by ojoilesanmi**
Task 2 Completed

### CODE REVIEW

**Comment by ojoilesanmi** [comment]
def task_2():
    full_name = " Ojo Ilesanmi"
    ID = '01808'
    language = 'Python'
    email = 'ojoilesanmi89@gmail.com'
    print('Hello world, this is {0} with HNGi7 ID {1} using {2} for stage 2 task'.format(full_name, ID, language), flush=True)

task_2()

**Comment by timmyCoder** [comment]
please resolve conflict

**Comment by ojoilesanmi** [comment]
Conflict?

Which conflict please? I made a correction and pushed back.

**Comment by ojoilesanmi** [comment]
I don't know what's going on actually. This is the message I get on my
terminal:
Your branch is up to date with 'origin/master'.
Is there a way you can help out with this?

**Pull request closed without merging**
