### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by 0m0hsam**
My task  in python programming language

### CODE REVIEW

**Comment by 0m0hsam** [comment]
Commit to master

**Comment by 0m0hsam** [comment]
Commit

**Comment by saucecodee** [comment]
Please your script should be in the scripts folder. And also make PR to the submission branch, not master

**Comment by 0m0hsam** [comment]
Commit

**Comment by 0m0hsam** [comment]
> Please your script should be in the scripts folder. And also make PR to the submission branch, not master
Hope I'm right How  should  i

**Pull request closed without merging**
