### PR TITLE
adding HNG-00452.js to the script folder

### PR DESCRIPTION
**Pull request by belovetech**
change added

### CODE REVIEW

**Comment by timmyCoder** [comment]
please fix conflicting files

**Comment by belovetech** [comment]
> please fix conflicting files

How can I fix the conflict pls?

**Comment by timmyCoder** [comment]
check online here for the error in the file, and fix in your IDE
then push again

**Comment by belovetech** [comment]
> check online here for the error in the file, and fix in your IDE
> then push again

What i can see is seeing my two committed file merging together and i don't really know how to delete the previous one.

**Comment by anubabajide** [comment]
If you want to change or modify a file, you can:
1. go to the submissions branch of the HNG repo.
2. Fork it
3. Locate the file and make your change
4. Then make a Pull Request back to submissions.

**Pull request closed without merging**
